### ISSUE TITLE
Ca un utilizator ANABI, vreau sa modific un bun minimal

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/anabi-gestiune-client#37]
Endpoint PUT api/assets/{assetId}

Guidelines: https://codeforromania.atlassian.net/wiki/spaces/ANABI/pages/423657490/API+Guidelines?atlOrigin=eyJpIjoiZjllNDc0MzE5MWQyNDM2MThjNmY0YjA4MGE1NzNjZmIiLCJwIjoiYyJ9

- [x] Frontend
- [x] Backend

**Comment by vlad2** [comment]
https://github.com/code4romania/anabi-gestiune-client/tree/issue-37-edit-asset

**Comment by bogdanconstantinescu** [comment]
A fost facut merge in master; se poate testa.

**Comment by RaduCStefanescu** [comment]
Issue asta e implementat, se poate inchide.
