### ISSUE TITLE
Ca un utilizator ANABI, vreau sa adaug un inculpat la un bun

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/anabi-gestiune-client#40]
Se pot adauga mai multi inculpati la un bun.

Wireframe: atasat

Campuri: (* inseamna camp obligatoriu)

Tip inculpat (PF sau PJ) *

In functie de ce alege (PF / PJ), apar un set de campuri.

# Persoana Fizica
Nume *
Prenume *
Nationalitate *
Identificator - pentru cei cu nationalitate RO este CNP; daca la Nationalitate au completat alta tara in afara de Romania, campul asta devine free form ca sa completeze anything they might need *
Data nasterii

# Persoana Juridica
Nume *
Tara de care apartine *
CUI (daca tara e Romania) *   /  Identificator (daca nu apartine de Romania) *

# Note
In screenshot apar 2 campuri, CNP si Identificator. Trebuie sa apara un singur camp (CNP/Identificator). 

![image](https://user-images.githubusercontent.com/15039873/53095876-83562100-3526-11e9-9d2e-a45d071d729d.png)

![image](https://user-images.githubusercontent.com/15039873/53095902-9537c400-3526-11e9-8d94-dcec8fcd7638.png)

Swagger:
![screenshot_2019-02-23 swagger ui](https://user-images.githubusercontent.com/1876933/53286588-81d06700-3779-11e9-9471-b01048601758.png)

**Comment by vlad2** [comment]
Work in progress de la Stefan Oproiu:

https://github.com/oproiustefan/anabi-gestiune-client/tree/add-defendant

**Comment by vlad2** [comment]
Oproiu Stefan [8:41 AM]
Modelul pentru adaugarea unui inculpat nu pare prea consistent, asa ca voi incerca sa fac o presupunere despre cum s-ar mapa la modelul formularului:
[idSerie] si [idNumber] nu apar deloc in formularul de adaugare/editare, deci nu vor putea fi introduse de aici
[identification] reprezinta acel identificator valabil numai daca nationalitatea/tara de origine nu este Romania
Daca tara este Romania, atunci nu se mai completeaza [identification], ci [identifierId], care e echivalent cu CNP (pt PF)/CUI (pt PJ), care trebuie neaparat sa fie validat ca un string ce contine numai cifre
[isPerson] e un flag care ne spune: true daca e vorba de PF si false daca e vorba de PJ
[name] reprezinta numele de familie in cazul PF sau numele firmei in cazul PJ
[birthdate] = data de nastere in cazul PF
[firstName] = prenumele in cazul PF
[nationality] = nationalitatea in cazul PF sau tara de origine in cazul PJ
Gresesc undeva?


@Oproiu Stefan  salut! are prioritate wireframeul, fata de ce e implementat in backend.Referitor la [identification], si [identifierId].
In backend e un apel
Person
GET
/api/person/identifiers
Returns identifiers in the database  (http://backend.anabi-dev.code4.ro/swagger/index.html).Daca rulezi chestia aia, si pui flagul "forPerson" true, vei obtine
[
 {
   "id": 1,
   "identifierType": "CNP"
 },
 {
   "id": 2,
   "identifierType": "Pasaport"
 }
]Deci: Daca persoana e PF, roman, o sa trimiti catre backend in [identification] CNP_ul ei, si in [identifierId] valoare "1" (care inseamna CNP). Daca persoana e PF, dar nu e roman, trimiti catre backend in [identification] ce a scris omul acolo, si la [identifierId] valoarea 2.  O sa pun asta in github in issue, ca sa continuam discutia acolo. Pt ca se pierd informatiile astea daca sunt scrise pe slack.

**Comment by vlad2** [comment]
Hello,

Nu se salveaza nimic in DB. 
Inteleg ca BE-ul e facut, dar nu e chemat din FE. 

Redeschid acest issue.

**Comment by RaduCStefanescu** [comment]
This looks like it implemented, we can close it.
