### ISSUE TITLE
Ca un utilizator ANABI, vreau sa listez spatiile de stocare existente

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/anabi-gestiune-client#42]
Trebuie o pagina noua, cu un tabel asemanator cu cel din pagina de listare bunuri ("Bunuri"), care insa sa aiba coloanele pentru Spatii de Stocare (Depozitare) din pagina de Entitati:
https://codeforromania.atlassian.net/wiki/spaces/ANABI/pages/267256067/Entit+

Si anume:
- ID
- Nume
- Tip
- Adresa - (toate campurile din adresa concatenate intr-un singur camp)

Ideal ar fi ca tabelul sa fie similar cu cel din "Bunuri" si anume sa aiba : 
- sortare pe coloane
- paginare (in frontend)
- cautare 

### Taskuri
- [x] Backend - actualizare endpoint sa intoarca campurile care trebuie 
- [x] Frontend - tabelul

**Comment by vlad2** [comment]
Hello, la backend e f bun API-ul de introducere. 

E un bug mic, in sensul ca nu se salveaza numarul de pe strada:

Request de adaugare:

```
{
  "name": "Spatiu 1",
  "storageSpaceType": "Contracted",
  "countyCode": "B",
  "city": "Bucharest",
  "street": "Splaiul Unirii",
  "building": "39",
  "details": "Detalii spatiu stocare"
}
```

Il adauga in baza, si primesc inapoi 201 Created si ID-ul creat. Deci foarte frumos.

Si cand listez:

```
[
  {
    "id": 1,
    "name": "Spatiu 1",
    "storageSpaceType": "Contracted",
    "addresss": {
      "id": 1,
      "county": {
        "id": 32,
        "name": "BUCUREȘTI",
        "abreviation": "B"
      },
      "street": "Splaiul Unirii",
      "city": "Bucharest",
      "building": null,
      "stair": null,
      "floor": null,
      "flatNo": null
    }
  }
]
```

Ma asteptam ca building sa fie 39, nu null.

**Comment by vlad2** [comment]
Hello,

Am introdus un spatiu de stocare in DB - prin SQL, nu stiu daca am pus query-ul bine, dar mi-a bagat in DB: 

`INSERT INTO StorageSpaces (UserCodeAdd, AddedDate, AddressId, Name, StorageSpacesType, Description) VALUES ('admin', getdate(), 5, 'Târgoviște', 1, NULL);
`

Si acum endpointul de API /storageSpaces intoarce:

`[{"name":"Târgovi?te","storageSpaceType":"Contracted","addresss":{"id":5,"county":{"id":26,"name":"BIHOR","abreviation":"BH"},"street":"strada","city":"bihor","building":"bloc","description":null},"id":5,"journal":null}]`

Cand dau click pe 'Spatii de stocare',  imi apare chestia asta: 
![Untitled](https://user-images.githubusercontent.com/1876933/61596192-22cc2c80-ac09-11e9-9c87-3ebc902d4d2c.png)

Ma asteptam:
- sa nu apara erori in consola.
- sa apara spatiile de depozitare.

Bug, redeschidem.

**Comment by Wydder** [comment]
1. Inteleg ca s-a modificat modelul la StorageSpace? Pot primi unul actualizat?
2. Din ce vad in cod ar trebui si un assetId StorageSpace-ul fiind e o propietate a unui bun!

**Comment by RaduCStefanescu** [comment]
@Wydder @RaduCStefanescu verifica modelul din frontend si backend

**Comment by RaduCStefanescu** [comment]
Testat, merge dupa ce s-a facut fix in backend pentru un type pe view.
<img width="1671" alt="Screenshot 2019-07-25 at 18 08 38" src="https://user-images.githubusercontent.com/15039873/61885887-493ee000-af07-11e9-99b1-19981db30331.png">

Am sa deschid un alt bug pentru caractere cu encodare speciala, cum se vede in print screen
