### ISSUE TITLE
Ca un utilizator ANABI, vreau sa sterg un inculpat al unui bun

### ISSUE THREAD

**Issue by vlad2** [code4romania/anabi-gestiune-client#51]
Ok, cam asa arata acum pagina de vizualizare a unui bun: 

![Screenshot_2019-03-30 Anabi](https://user-images.githubusercontent.com/1876933/55275020-5bf23100-52e8-11e9-88c2-d22c242df330.png)

Momentan, se pot adauga inculpati la bun, dar nu se pot sterge. Dorim sa se poata sterge. 

Trebuie implemntat si BE, si FE. 

- [x] Backend - endpoint nou de stergere al unui inculpat
- [x] Frontend

**Comment by vlad2** [comment]
O sa faca Ștefan Oproiu și BE si FE.

**Comment by vlad2** [comment]
PR FE:
https://github.com/code4romania/anabi-gestiune-client/pull/58

BE: O sa lucreze Ștefan zilele astea.

**Comment by vlad2** [comment]
PR BE:

https://github.com/code4romania/anabi-gestiune-api/pull/126

**Comment by vlad2** [comment]
PR FE: https://github.com/code4romania/anabi-gestiune-client/pull/58

PR_ul de Backend a fost merge-uit.

**Comment by RaduCStefanescu** [comment]
@bogdanconstantinescu pare ca si pull  requestul de frontend a fost merged:
https://github.com/code4romania/anabi-gestiune-client/pull/58

Putem sa mutam in testare acest issue?

**Comment by bogdanconstantinescu** [comment]
Eroarea care vine de la backend e `{"Message":"Value cannot be null.\nParameter name: entity","Errors":["Value cannot be null.\nParameter name: entity"]}`.
Partea de frontend e ok, cand bugul de pe backend e rezolvat se poate muta direct in testare.

**Comment by RaduCStefanescu** [comment]
Mutat inapoi in Reopened, trebuie fixata problema pe backend.

**Comment by RaduCStefanescu** [comment]
Retestat dupa ce se face merge la https://github.com/code4romania/anabi-gestiune-api/pull/149

**Comment by Puiu** [comment]
BE e ok acum, merge si pe AWS

**Comment by RaduCStefanescu** [comment]
Testat dupa fixul pe BE, merge partea de stergere.
Am sa inchid acest issue, dar am sa deschid un bug pe partea de usability, dupa ce se da click pe butonul de Sterge ma astept sa se faca refresh la pagina de afisare a assetului, din care a disparut bunul sters.
Momentan nu se intampla asta.
