### ISSUE TITLE
Ca un utilizator ANABI, vreau sa vad adresa unui bun.

### ISSUE THREAD

**Issue by vlad2** [code4romania/anabi-gestiune-client#57]
GET /api/assets/{id}/address

- [x] Backend - endpoint nou GET  sa intoarca adresa bunului 
- [x] Frontend - sa afiseze adresa bunului in "Detalii bun"

**Comment by vlad2** [comment]
Bogdan zice ca e mai simplu sa facem un endpoint nou care sa intoarca addresa bunului, ca la celelalte proprietati (inculpat, spatiu de stocare). 

GET /api/assets/{id}/address

**Comment by vlad2** [comment]
Preia Alex Albu partea de backend.

**Comment by Puiu** [comment]
BE-ul este gata

**Comment by RaduCStefanescu** [comment]
@Puiu @bogdanconstantinescu issue asta pare ca e merged si pe FE si pe BE, cred ca poate sa fie mutat in testare

**Comment by RaduCStefanescu** [comment]
Testat, e totul ok, dar dupa ce se adauga o adresa ar tb sa fie disabled butonul de Adaugare adresa.
Am deschis un bug nou https://github.com/code4romania/anabi-gestiune-client/issues/71
