### ISSUE TITLE
Un bun nou adaugat nu poate fi vizualizat

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/anabi-gestiune-client#70]
**Bug description**
Un asset adaugat in dashboard nu poate fi vizualizat.

**Step to reproduce it**
- adauga un asset nou in dashboard
- click pe asset pentru vizualizare
- componenta de asset view nu se incarca

**Expected behavior**
Dupa adaugarea unui nou asset, ca user pot sa vizualizez acest nou asset.

**Additional info**
Bug pentru API: https://github.com/code4romania/anabi-gestiune-api/issues/146
API intoarce 200 OK pentru un asset care nu are address. API response nu intoarce niciun obiect, in cazul in care nu exista address pentru asset.

**Comment by RaduCStefanescu** [comment]
Bugul pentru backend https://github.com/code4romania/anabi-gestiune-api/issues/146 a fost rezolvat. Intoarce o adresa empty cand nu exista adrese adaugate pe un bun.

**Comment by andrei1489** [comment]
Il pot lua eu. Problema pe FE e cu bunurile care au lipsa adresa si defendant.

**Comment by RaduCStefanescu** [comment]
This issue is fixed in #76
