### ISSUE TITLE
Afisare caractere cu encodare speciala

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/anabi-gestiune-client#73]
Denumirile de judete sau orice alt string care contine caractere cu encodare speciala trebuie sa fie afisate corect
Exemplu:

<img width="1671" alt="Screenshot 2019-07-25 at 18 08 38" src="https://user-images.githubusercontent.com/15039873/61887494-6923d300-af0a-11e9-8e58-a22f661b0c8a.png">

**Comment by DavidManda** [comment]
Am incercat sa gasesc care este problema, si am ajuns la [http://backend.anabi-dev.code4.ro/api/storageSpaces](url), care contine `[{"name":"Târgovi?te"...` Problema este ca nu am reusit sa gasesc de unde vin acele date si unde este creeata acea pagina. Problema ar trebui sa fie acolo, nu pe partea de client. Din ce am vazut, in alte parti, caracterele cu encodare speciala sunt primite si afisate corect, deci cred ca problema este la data source.

**Comment by RaduCStefanescu** [comment]
Multumesc @DavidManda am facut update in DB cu numele cu diacritice, se afiseaza corect in frontend.
