### ISSUE TITLE
Installing the app is failing

### ISSUE THREAD

**Issue by DavidManda** [code4romania/anabi-gestiune-client#74]
**Bug description**
Running `sudo npm install` inside the root folder fails with:
``gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/user/anabi-gestiune-client-master/node_modules/node-sass/.node-gyp'
``

**Step to reproduce it**
Following the installation steps on a Centos7 machine. 
npm and node are installed and at the latest stable version.

**Expected behavior**
Successful installation.

**Additional info**
I also tried using `sudo chown -R user:user /home/user/anabi-gestiune-client-master/node_modules/` but I still get the same error.

**Comment by bogdanconstantinescu** [comment]
`npm install` should not be ran as `root`, check the details here: https://github.com/angular/angular-cli/issues/6800#issuecomment-311356321

**Comment by DavidManda** [comment]
I see, thank you
